### ISSUE TITLE
整数除以0报错

### ISSUE THREAD

**Issue by Lost-little-dinosaur** [chenbinghui1/DSL#25]
大佬们好，想问一个问题
我按照README中的教程一步一步走下来，但在执行这一步时
![image](https://user-images.githubusercontent.com/82520400/203042830-aa9010d1-b084-4fd1-a5ff-f8033a3356ce.png)

发生了报错，信息如下：
![image](https://user-images.githubusercontent.com/82520400/203042629-66459fae-b657-4401-bff6-29dd1d3c83fa.png)

我不知道为什么，网上搜了一下也没有什么相关信息，求教

**Comment by Lost-little-dinosaur** [comment]
这里是更详细的错误信息


root@2ee107b62013:/home/keyan/image_analysis/src/my_DSL/DSL# ./demo/model_train/baseline_coco.sh
/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 202, in <module>
    main()
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 120, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 202, in <module>
    main()
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 120, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 202, in <module>
    main()
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 120, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 202, in <module>
    main()
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 120, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 202, in <module>
    main()
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 120, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 202, in <module>
    main()
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 120, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 202, in <module>
    main()
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 120, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 202, in <module>
    main()
  File "/home/keyan/image_analysis/src/my_DSL/DSL/./tools/train.py", line 120, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/runner/dist_utils.py", line 31, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 238) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-11-21_11:39:40
  host      : 2ee107b62013
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 239)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-11-21_11:39:40
  host      : 2ee107b62013
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 240)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-11-21_11:39:40
  host      : 2ee107b62013
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 241)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2022-11-21_11:39:40
  host      : 2ee107b62013
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 242)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2022-11-21_11:39:40
  host      : 2ee107b62013
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 243)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2022-11-21_11:39:40
  host      : 2ee107b62013
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 244)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2022-11-21_11:39:40
  host      : 2ee107b62013
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 245)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-21_11:39:40
  host      : 2ee107b62013
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 238)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
